// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Carousel from "stimulus-carousel";
import Dropdown from "stimulus-dropdown";
application.register("carousel", Carousel);
application.register("dropdown", Dropdown);



import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import SubmitController from "./submit_controller"
application.register("submit", SubmitController)

import TimetableController from "./timetable_controller"
application.register("timetable", TimetableController)

import LightboxController from "./lightbox_controller"
application.register("lightbox", LightboxController)
