// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import SlideshowController from "./slideshow_controller"
import HeaderController from "./header_controller"
import TimetableController from "./timetable_controller"
import Carousel from 'stimulus-carousel'
import 'swiper/css/bundle'

application.register("hello", HelloController)
application.register("slideshow", SlideshowController)
application.register("header", HeaderController)
application.register("timetable", TimetableController)
application.register('carousel', Carousel)

