// Entry point for the build script in your package.json
import "@hotwired/turbo-rails"
// import "./slick.min.js"
// import "./bootstrap.min.js"
// import "./vendor/jquery-3.6.0.min.js"
// import "./jquery.magnific-popup.min.js"
// import "./jquery.counterup.min.js"
// import "./jquery-ui.min.js"
// import "./imagesloaded.pkgd.min.js"
// import "./isotope.pkgd.min.js"
import "./add_jquery.js"
import "./slick.min.js"
import "./jquery.magnific-popup.min.js"
import "./imagesloaded.pkgd.min.js"
import "./jquery.counterup.min.js"
import "./jquery-ui.min.js"
import "./nice-select.min.js"
import "./gsap.min.js"
import "./main.js"

