# BALLET LEVELS
mummy = BalletLevel.create!(name: "Mummy and Me", description: "A fun, creative class designed for wee dancers from 18months - 2 years. This class is for Mums, Dads or Grandparents to attend along with their tiny dancer! \n")
pre_school = BalletLevel.create!(name: "Pre-school", description: "Creative and imaginative classes designed to develop coordination, musicality and basic movements! \n\n For ages 3-4 years.\n")
pre_primary = BalletLevel.create!(name: "Pre-Primary", description: "Creative and imaginative Movement whilst developing coordination, control, musicality and expression and introducing ballet foundations at an appropriate level. This class follows the Royal Academy of Dance “Pre-Primary in Dance” Syllabus. \n\n For ages 5-6 years.\n")
primary = BalletLevel.create!(name: "Primary", description: "Developing coordination, control and musicality, along with performance and expression. This class is taught in a fun, imaginative way whilst still introducing the basics of ballet at an appropriate level. This class follows the Royal Academy of Dance “Primary in Dance” Syllabus. \n\n For ages 6-7 years.\n")
grade_1 = BalletLevel.create!(name: "Grade 1", description: "Grade 1's work on systematically developing solid foundational classical technique based on the Royal Academy of Dance pedagogy. All classes include strength and conditioning and national character training. \n\n Ages 7+ \n")
grade_2 = BalletLevel.create!(name: "Grade 2", description: "Grade 2's work on systematically developing solid foundational classical technique based on the Royal Academy of Dance pedagogy. All classes include strength and conditioning and national character training. \n\n Ages 7+ \n")
grade_3 = BalletLevel.create!(name: "Grade 3", description: "Grade 3's work on systematically developing solid foundational classical technique based on the Royal Academy of Dance pedagogy. All classes include strength and conditioning and national character training. \n\n Ages 7+ \n")
grade_4 = BalletLevel.create!(name: "Grade 4", description: "Grades 4's continue to develop on the foundations of classical ballet, while also introducing artistry and more sophisticated performance skills. All classes are based on the Royal Academy of Dance pedagogy. All classes include strength and conditioning and national character training. \n\n Ages 10+ \n")
grade_5 = BalletLevel.create!(name: "Grade 5", description: "Grades 5's continue to develop on the foundations of classical ballet, while also introducing artistry and more sophisticated performance skills. All classes are based on the Royal Academy of Dance pedagogy. All classes include strength and conditioning and national character training, along with beginning pre-pointe training in Grade 5 for female dancers.\n\n Enroling in this class gives the option to attend 1 bonus open class (2 class per week enrolment only). \n\n Ages 10+ \n")
grade_6 = BalletLevel.create!(name: "Grade 6", description: "Grades 6's build on foundations of classical ballet, while also going into more detailed artistry and more sophisticated performance skills. Learning a variety of styles in national character and free movement, dancers will develop a sophisticated classical style with attention to detail and nuance. All classes are based on the Royal Academy of Dance pedagogy. All classes include strength and conditioning and national character training. \n\n Ages 12+ \n")
intermediate_foundation = BalletLevel.create!(name: "Intermediate Foundation", description: "Intermediate Foundation is the first of the vocational levels which focus on developing aspiring dancers in their technique, artistry, and control. This grade introduces pointe work for the first time and free enchainment work. All classes are based on the Royal Academy of Dance syllabus pedagogy. All classes include strength and conditioning. Included in this is an occasional class with a live pianist. \n\n Ages 12+ \n")
intermediate = BalletLevel.create!(name: "Intermediate", description: "This is the second of the vocational levels which focus on developing aspiring dancers in their technique, artistry, and control. This grade continues to develop pointe work and free enchainment work. All classes are based on the Royal Academy of Dance syllabus pedagogy. All classes include strength and conditioning. Included in this is an occasional class with a live pianist. \n\n Ages 12+ \n")
advanced_foundation = BalletLevel.create!(name: "Advanced Foundation", description: "Prerequisite - must have passed RAD Intermediate. \n\n Advanced Foundation is the third of the vocational levels which focus on developing aspiring dancers in their technique, artistry, and control at an advanced level. This grade works on pointe work at an advanced level and continues to include free enchainment work. All classes are based on the Royal Academy of Dance syllabus pedagogy. All classes include strength and conditioning. Included in this is an occasional class with a live pianist. \n\n Ages 13+ \n")
booty_barre = BalletLevel.create!(name: "Bootybarre", description: "Booty Barre is a fun, energetic work out that fuses techniques from dance, Pilates and yoga that will tone, define and chisel the whole body! BootyBarre is the perfect combinations of strength and flexibility with and added cardiovascular element utilising the barre. This is an internationally renowned fitness program designed to accomodate most fitness levels, while being low impact but high energy. Taught by a certified Instructor. \n\n Ages 15+ \n")
open_level = BalletLevel.create!(name: "Open Class", description: "An open class is an additional class that has predominantly unset work ( the teacher will design new exercises for each class as opposed to syllabus work). This class is an important part of dance in learning to pick new exercises up quickly and accurately, while still developing technique and strength. \n\n These classes are available to those who have enroled in a class Grade 5 or above.\n")

#COSTS
mummy_price_1 = Cost.create!(ballet_level_id: 1, amount: 65.00, condition: "1 class per week for an 8 week term")
pre_school_price_1 = Cost.create!(ballet_level_id: 2, amount: 100.00, condition: "1 class per week")
pre_primary_price_1 = Cost.create!(ballet_level_id: 3, amount: 125.00, condition: "1 class per week")
primary_price_1 = Cost.create!(ballet_level_id: 4, amount: 135.00, condition: "1 class per week")
grade_1_price_1 = Cost.create!(ballet_level_id: 5, amount: 275.00, condition: "2 classes per week")
grade_1_price_2 = Cost.create!(ballet_level_id: 5, amount: 137.50, condition: "1 class per week (for those not sitting exams)")
grade_2_price_1 = Cost.create!(ballet_level_id: 6, amount: 275.00, condition: "2 classes per week")
grade_2_price_2 = Cost.create!(ballet_level_id: 6, amount: 137.50, condition: "1 class per week (for those not sitting exams)")
grade_3_price_1 = Cost.create!(ballet_level_id: 7, amount: 275.00, condition: "2 classes per week")
grade_3_price_2 = Cost.create!(ballet_level_id: 7, amount: 137.50, condition: "1 class per week (for those not sitting exams)")
grade_4_price_1 = Cost.create!(ballet_level_id: 8, amount: 315.00, condition: "2 classes per week")
grade_4_price_2 = Cost.create!(ballet_level_id: 8, amount: 157.50, condition: "1 class per week (for those not sitting exams)")
grade_5_price_1 = Cost.create!(ballet_level_id: 9, amount: 315.00, condition: "2 classes per week")
grade_5_price_2 = Cost.create!(ballet_level_id: 9, amount: 157.50, condition: "1 class per week (for those not sitting exams)")
grade_6_price_1 = Cost.create!(ballet_level_id: 10, amount: 350.00, condition: "2 classes per week + 1 optional open class")
intermediate_foundation_price_1 = Cost.create!(ballet_level_id: 11, amount: 365.00, condition: "2 classes per week + 1 open class")
intermediate_price_1 = Cost.create!(ballet_level_id: 12, amount: 365.00, condition: "2 classes per week + 1 open class")
advanced_foundation_price_1 = Cost.create!(ballet_level_id: 13, amount: 365.00, condition: "2 classes per week + 1 open class")
booty_barre_price_1 = Cost.create!(ballet_level_id: 14, amount: 16.00, condition: "per class")

# TIMETABLES
timetable_1 = Timetable.create!(term: '1', start_date: DateTime.new(2023, 2, 17), end_date: DateTime.new(2023, 4, 6))


#BALLET CLASSES
mummy_class = BalletClass.create!(ballet_level_id: 1) # (has enrolments)
preschool_class = BalletClass.create!(ballet_level_id: 2) # (has enrolments)
pre_primary_class = BalletClass.create!(ballet_level_id: 3) # (has enrolments)
primary_class = BalletClass.create!(ballet_level_id: 4) # (has enrolments)
grade_1_class = BalletClass.create!(ballet_level_id: 5) # (has enrolments)
grade_2_class = BalletClass.create!(ballet_level_id: 6) # (has enrolments)
grade_3_class = BalletClass.create!(ballet_level_id: 7) # (has enrolments)
grade_4_class = BalletClass.create!(ballet_level_id: 8) # (has enrolments)
intermediate_foundation_class = BalletClass.create!(ballet_level_id: 11) # (has enrolments)
intermediate_class = BalletClass.create!(ballet_level_id: 12) # (has enrolments)
advanced_foundation_class = BalletClass.create!(ballet_level_id: 13) # (has enrolments)
booty_barre_class = BalletClass.create!(ballet_level_id: 14) # (has enrolments)
open_class = BalletClass.create!(ballet_level_id: 15) # (has enrolments)

#CLASSTIMES
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 2, day_of_week: "Saturday", start_time: "10:00am", end_time: "10:30am")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 3, day_of_week: "Saturday", start_time: "10:30am", end_time: "11:15am")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 5, day_of_week: "Saturday", start_time: "11:15am", end_time: "12:00pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 11, day_of_week: "Saturday", start_time: "12:00pm", end_time: "1:30pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 4, day_of_week: "Monday", start_time: "3:30pm", end_time: "4:15pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 5, day_of_week: "Monday", start_time: "4:15pm", end_time: "5:15pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 9, day_of_week: "Monday", start_time: "5:15pm", end_time: "6:15pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 10, day_of_week: "Monday", start_time: "6:15pm", end_time: "7:30pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 13, day_of_week: "Tuesday", start_time: "4:45pm", end_time: "6:00pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 9, day_of_week: "Tuesday", start_time: "6:10pm", end_time: "7:20pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 1, day_of_week: "Wednesday", start_time: "10:00am", end_time: "10:20")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 2, day_of_week: "Wednesday", start_time: "11:00am", end_time: "11:30am")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 13, day_of_week: "Wednesday", start_time: "5:30pm", end_time: "6:30pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 11, day_of_week: "Wednesday", start_time: "6:45pm", end_time: "8:00pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 7, day_of_week: "Thursday", start_time: "4:30pm", end_time: "5:30pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 6, day_of_week: "Thursday", start_time: "3:30pm", end_time: "4:30pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 8, day_of_week: "Thursday", start_time: "5:30pm", end_time: "6:30pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 6, day_of_week: "Friday", start_time: "3:30pm", end_time: "4:30pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 7, day_of_week: "Friday", start_time: "4:30pm", end_time: "5:30pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 8, day_of_week: "Friday", start_time: "5:30pm", end_time: "6:30pm")
ClassTime.create!(timetable_id: Timetable.first.id, ballet_class_id: 10, day_of_week: "Friday", start_time: "6:30pm", end_time: "7:45pm")



# ATTACH BALLET LEVEL PICTURES
mummy.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "mummyandme.webp")), filename: 'mummyandme.webp')
pre_school.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "preschool.webp")), filename: 'preschool.webp')
pre_primary.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "preprimary.webp")), filename: 'pre_primary.webp')
primary.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "primary.webp")), filename: 'primary.webp')
grade_1.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "grade1.webp")), filename: 'grade1.webp')
grade_2.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "grade2.webp")), filename: 'grade2.webp')
grade_3.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "grade3.webp")), filename: 'grade3.webp')
grade_4.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "grade4.webp")), filename: 'grade4.webp')
grade_5.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "grade5.webp")), filename: 'grade5.webp')
grade_6.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "grade6.webp")), filename: 'grade6.webp')
intermediate_foundation.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "inter-found.webp")), filename: 'inter-found.webp')
intermediate.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "intermediate.webp")), filename: 'intermediate.webp')
advanced_foundation.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "adv-found.webp")), filename: 'adv-found.webp')
booty_barre.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "bootybarre.webp")), filename: 'bootybarre.webp')
open_level.picture.attach(io: File.open(Rails.root.join("app", "assets", "images", "classes", "open.webp")), filename: 'open.webp')

#GALLERY
my_gallery = Gallery.create!(title: "homepage gallery")
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo1.webp")), filename: 'photo1.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo2.webp")), filename: 'photo2.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo3.webp")), filename: 'photo3.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo4.webp")), filename: 'photo4.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo5.webp")), filename: 'photo5.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo6.webp")), filename: 'photo6.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo7.webp")), filename: 'photo7.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo8.webp")), filename: 'photo8.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo9.webp")), filename: 'photo9.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo10.webp")), filename: 'photo10.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo11.webp")), filename: 'photo11.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo12.webp")), filename: 'photo12.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo13.webp")), filename: 'photo13.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo14.webp")), filename: 'photo14.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo15.webp")), filename: 'photo15.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo16.webp")), filename: 'photo16.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo17.webp")), filename: 'photo17.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo18.webp")), filename: 'photo18.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo19.webp")), filename: 'photo19.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo20.webp")), filename: 'photo20.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo21.webp")), filename: 'photo21.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo22.webp")), filename: 'photo22.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo23.webp")), filename: 'photo23.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo24.webp")), filename: 'photo24.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo25.webp")), filename: 'photo25.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo26.webp")), filename: 'photo26.webp')
my_gallery.pictures.attach(io: File.open(Rails.root.join("app", "assets", "images", "gallery", "photo27.webp")), filename: 'photo27.webp')
